#!/bin/sh
set -e
PATH="$PATH:/usr/local/bin"

if [ $(id -u) -ne 0 ]; then
	echo "Please run as root" >&2
	exit 1
fi

expressvpn preferences set force_vpn_dns true
expressvpn preferences set network_lock on
expressvpn preferences set preferred_protocol udp
expressvpn preferences set send_diagnostics false

expressvpn connect $@
expvpn-iptables-setup
