#!/bin/sh
set -e

# Set default rules to be DROP.
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
ip6tables -P INPUT DROP
ip6tables -P OUTPUT DROP
ip6tables -P FORWARD DROP

# Reset all rules.
iptables -F INPUT
iptables -F OUTPUT
iptables -F FORWARD
ip6tables -F INPUT
ip6tables -F OUTPUT
ip6tables -F FORWARD
